### ISSUE TITLE
Cannot find trajectory_control server

### ISSUE THREAD

**Issue by JChangarirang** [gtrll/piper#2]
Hi, I am trying to run PIPER with example config and problem provided,
but getting 'Cannot find trajectory_control server' error.

**Comment by mhmukadam** [comment]
You need to have an action sever set up in your real/simulated robot's API. See ```trajectory_control_topic``` in [robot config](https://github.com/gtrll/piper/blob/master/doc/config.md).

**Comment by tsijs** [comment]
Where could I find the vector package used in the example s.t. I can run the example_problem?

**Comment by mhmukadam** [comment]
Well, vector is a custom robot with a mobile base and a Jaco arm. There are packages/documentation [here](https://github.com/HLP-R/hlpr_documentation/wiki) if you want to use the simulator.
