### ISSUE TITLE
Cannot find trajectory_control server '/vector/full_body_controller/trajectory'

### ISSUE THREAD

**Issue by rolling0707** [gtrll/piper#3]
"roslaunch piper steap_interface.launch", then I get this result ------ "Cannot find trajectory_control server '/vector/full_body_controller/trajectory'.  

what server I should connect ?

**Comment by mhmukadam** [comment]
You need to have an action sever set up in your real/simulated robot's API. See ```trajectory_control_topic``` in [robot config](https://github.com/gtrll/piper/blob/master/doc/config.md).
