### ISSUE TITLE
STEAP compilation -- broken gtsam call

### ISSUE THREAD

**Issue by sashalambert** [gtrll/piper#5]
Compilation error on STEAP interface:
```
/usr/local/include/gpmp2/planner/ISAM2TrajOptimizer-inl.h:106:63: error: no matching function for call to ‘gtsam::ISAM2::update(gtsam::NonlinearFactorGraph&, gtsam::Values&, std::vector<long unsigned int>&)’
   isam_.update(inc_graph_, init_values_, removed_factor_index_);
```
Latest GTSAM version (commit:6f8bfe0) has the following ISAM2 `update` call:

gtsam::ISAM2Result gtsam::ISAM2::update(const gtsam::NonlinearFactorGraph&, const gtsam::Values&, const FactorIndices&)

using the `FactorIndices` typdef.

**Comment by mhmukadam** [comment]
Yes, the ISAM2 API slightly changed on the GTSAM side recently. update() function now uses FactorIndices which is typedef from FastVector<size_t>. This affected the GPMP2 API and is now updated appropriately. If you pull and make check install GPMP2 and try PIPER again, the compilation error should go away.
